name: Metrics Smoke Test

on:
  push:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Import + count
        run: |
          python -c "from engine.metrics.api import get_summary; s=get_summary(); print(s); assert s['total_metrics']>=200"